name: Build FHIR Converter API

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build FHIR Converter API
        uses: docker/build-push-action@v3
        with:
          context: ./src/FHIRConverterAPI
          file: ./src/FHIRConverterAPI/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
