name: Test fhir-converter

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  unit-test-dotnet-fhir-converter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Run tests
        run: dotnet test --filter FullyQualifiedName~Converter.UnitTests

  functional-test-dotnet-fhir-converter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Run tests
        run: dotnet test --filter FullyQualifiedName~Converter.FunctionalTests
